// Mock data for available driver rides
export const rideList = [
  {
    departureTime: '09:00',
    from: 'Karachi',
    to: 'Hyderabad',
    seatAvailable: 2,
    seatFilled: 1,
    driverName: 'Ali Khan',
    driverPhone: '+923001234567',
    driverCarType: 'Toyota Corolla',
    driverAvatar: '@/assets/images/image.png',
    carPlate: 'ABC-1234',
    carPhoto: '@/assets/images/carphoto.jpg',
  },
  {
    departureTime: '10:30',
    from: 'Karachi',
    to: 'Hyderabad',
    seatAvailable: 3,
    seatFilled: 2,
    driverName: 'Sara Ahmed',
    driverPhone: '+923004567890',
    driverCarType: 'Honda Civic',
    driverAvatar: '@/assets/images/image.png',
    carPlate: 'XYZ-5678',
    carPhoto: '@/assets/images/carphoto.jpg',
  },
  {
    departureTime: '11:15',
    from: 'Karachi',
    to: 'Hyderabad',
    seatAvailable: 1,
    seatFilled: 3,
    driverName: 'Bilal Sheikh',
    driverPhone: '+923008765432',
    driverCarType: 'Suzuki Swift',
    driverAvatar: '@/assets/images/image.png',
    carPlate: 'LMN-2468',
    carPhoto: '@/assets/images/carphoto.jpg',
  },
  {
    departureTime: '12:00',
    from: 'Karachi',
    to: 'Hyderabad',
    seatAvailable: 4,
    seatFilled: 0,
    driverName: 'Fatima Noor',
    driverPhone: '+923002468135',
    driverCarType: 'Kia Picanto',
    driverAvatar: '@/assets/images/image.png',
    carPlate: 'DEF-1357',
    carPhoto: '@/assets/images/carphoto.jpg',
  },
  {
    departureTime: '15:00',
    from: 'Karachi',
    to: 'Hyderabad',
    seatAvailable: 4,
    seatFilled: 3,
    driverName: 'SIM BOON XUN',
    driverPhone: '+601139303135',
    driverCarType: 'Perodua Myvi',
    driverAvatar: '@/assets/images/image.png',
    carPlate: 'SWD 9459',
    carPhoto: '@/assets/images/carphoto.jpg',
  },
  {
    departureTime: '22:00',
    from: 'Karachi',
    to: 'Hyderabad',
    seatAvailable: 4,
    seatFilled: 2,
    driverName: 'SIM BOON XUN',
    driverPhone: '+601139303135',
    driverCarType: 'Perodua Myvi',
    driverAvatar: '@/assets/images/image.png',
    carPlate: 'SWD 9459',
    carPhoto: '@/assets/images/carphoto.jpg',
  },
  {
    departureTime: '13:39',
    from: 'Karachi',
    to: 'Hyderabad',
    seatAvailable: 4,
    seatFilled: 3,
    driverName: 'SIM',
    driverPhone: '+601139303135',
    driverCarType: 'Perodua Myvi',
    driverAvatar: '@/assets/images/image.png',
    carPlate: 'SWD 9459',
    carPhoto: '@/assets/images/carphoto.jpg',
  },
]; 